version: '3.8'
services:
  mongodb:
    image: candis/mongo-replica-set
    container_name: mongodb
    ports:
      - '27017:27017'
      - '27018:27018'
      - '27019:27019'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
